#!/bin/sh

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

case "$1" in
    lock)
        $HOME/.config/i3/blurlock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        $HOME/.config/i3/blurlock && $logind suspend
        ;;
    hibernate)
        $HOME/.config/i3/blurlock && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
