# /etc/hosts is intentionally hand-managed, NOT generated by NixOS.
#
# Disabling the generated file lets dev/internal host overrides live directly in
# /etc/hosts — kept out of this public repo, and editable without a rebuild.
# NixOS leaves unmanaged /etc files alone, so the file persists across switches
# and reboots. Trade-off: it's no longer declarative, and the boilerplate that
# NixOS used to add (localhost, this host's name) is now your responsibility.
#
# Starter /etc/hosts (recreate on a fresh install):
#
#   127.0.0.1   localhost
#   ::1         localhost
#   127.0.0.2   tehunicorn
#
#   # local dev override example
#   127.0.0.1 app.example.internal auth.example.internal
#
#   # internal clusters (ngc2 / sat-lab) — add by hand when needed
{ lib, ... }:

{
  environment.etc.hosts.enable = lib.mkForce false;
}
