#!/bin/sh

# vim: ft=sh

# Accept Xcode License

cd ~/.dotfiles

# Bootstrap oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  mkdir -p ~/.oh-my-zsh/custom/plugins/eddiezane
  mkdir -p ~/.oh-my-zsh/custom/themes
fi

# Bootstrap Vundle
if [ ! -d ~/.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

# Remove file created by strap
rm -rf ~/.gitconfig

for i in git node ruby tmux vim zsh; do
  stow $i
done

if [ -d ~/.vim/bundle ]; then
  echo | echo | vim +PluginInstall +qall
  # ~/.vim/bundle/YouCompleteMe/install.py --clang-completer --tern-completer --gocode-completer
fi
