#!/bin/sh

# vim: ft=sh

cd ~/.dotfiles

# Bootstrap oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  mkdir -p ~/.oh-my-zsh/custom/plugins/eddiezane
  mkdir -p ~/.oh-my-zsh/custom/themes
fi
